import streamlit as st
import folium
from streamlit_folium import st_folium
from shapely.geometry import Polygon, shape, mapping, MultiPolygon
from shapely.ops import transform, unary_union
import pyproj
import math
import json
import io
from datetime import datetime

# ============================================================================
# ФУНКЦИИ КОНВЕРТАЦИИ КООРДИНАТ
# ============================================================================

def wgs84_to_meters(geom):
    """Конвертация из WGS84 (градусы) в Web Mercator (метры) для геометрических операций"""
    project = pyproj.Transformer.from_crs("EPSG:4326", "EPSG:3857", always_xy=True)
    return transform(project.transform, geom)

def meters_to_wgs84(geom):
    """Конвертация из Web Mercator (метры) в WGS84 (градусы)"""
    project = pyproj.Transformer.from_crs("EPSG:3857", "EPSG:4326", always_xy=True)
    return transform(project.transform, geom)

def calculate_geodesic_area(geom_wgs84):
    """
    Точный геодезический расчет площади на эллипсоиде WGS84
    Возвращает площадь в квадратных метрах (без искажений проекции)
    """
    if geom_wgs84 is None or geom_wgs84.is_empty:
        return 0
    
    geod = pyproj.Geod(ellps="WGS84")
    
    if geom_wgs84.geom_type == 'Polygon':
        exterior_coords = list(geom_wgs84.exterior.coords)
        lons = [c[0] for c in exterior_coords]
        lats = [c[1] for c in exterior_coords]
        _, area = geod.polygon_area_perimeter(lons, lats)
        return abs(area)
        
    elif geom_wgs84.geom_type == 'MultiPolygon':
        total_area = 0
        for polygon in geom_wgs84.geoms:
            exterior_coords = list(polygon.exterior.coords)
            lons = [c[0] for c in exterior_coords]
            lats = [c[1] for c in exterior_coords]
            _, area = geod.polygon_area_perimeter(lons, lats)
            total_area += abs(area)
        return total_area
    
    return 0

# ============================================================================
# ФУНКЦИИ ДЛЯ 3D ЭКСПОРТА
# ============================================================================

def create_obj_file(geometry_meters, height_meters, filename="building.obj"):
    """Создание OBJ файла из 2D полигона с экструзией"""
    if geometry_meters is None or geometry_meters.is_empty:
        return ""
    
    # Получаем координаты полигона
    coords = []
    if geometry_meters.geom_type == 'Polygon':
        coords = list(geometry_meters.exterior.coords)
    elif geometry_meters.geom_type == 'MultiPolygon':
        coords = list(geometry_meters.geoms[0].exterior.coords)
    else:
        return ""
    
    if len(coords) < 3:
        return ""
    
    # Находим минимальные координаты для центрирования
    min_x = min(c[0] for c in coords)
    min_y = min(c[1] for c in coords)
    
    obj_content = []
    obj_content.append("# Building 3D Model")
    obj_content.append("# Generated by Urban Potential Analyzer")
    obj_content.append(f"# Height: {height_meters:.1f}m")
    obj_content.append("")
    
    # Вершины основания (z = 0)
    for x, y in coords[:-1]:  # Последняя точка = первой
        obj_content.append(f"v {x - min_x:.2f} {y - min_y:.2f} 0.0")
    
    # Вершины крыши (z = height)
    for x, y in coords[:-1]:
        obj_content.append(f"v {x - min_x:.2f} {y - min_y:.2f} {height_meters:.2f}")
    
    obj_content.append("")
    
    n = len(coords) - 1
    if n < 3:
        return ""
    
    # Грани основания (нижняя)
    base_face = "f " + " ".join(str(i+1) for i in range(n))
    obj_content.append(base_face)
    
    # Грани крыши (верхняя)
    roof_face = "f " + " ".join(str(i+1+n) for i in range(n))
    obj_content.append(roof_face)
    
    # Боковые грани
    for i in range(n):
        next_i = (i + 1) % n
        side_face = f"f {i+1} {next_i+1} {next_i+1+n} {i+1+n}"
        obj_content.append(side_face)
    
    return "\n".join(obj_content)

# ============================================================================
# ФУНКЦИИ ДЛЯ ИНСОЛЯЦИИ
# ============================================================================

def calculate_shadow_length(building_height, latitude=55.75):
    """
    Упрощенный расчет длины тени от здания (зимнее солнцестояние - худший случай)
    """
    # Угол солнца в полдень на зимнее солнцестояние (21 декабря)
    solar_angle = 90 - abs(latitude + 23.45)
    solar_angle_rad = math.radians(max(solar_angle, 5))
    
    shadow_length = building_height / math.tan(solar_angle_rad)
    return shadow_length

# ============================================================================
# КЛАСС АНАЛИЗАТОРА
# ============================================================================

class UrbanPotentialAnalyzer:
    def __init__(self, parcel_geom_meters, parcel_geom_wgs84, pzz_config, restrictions_geom=None):
        """
        :param parcel_geom_meters: геометрия в метрах (для операций buffer/difference)
        :param parcel_geom_wgs84: геометрия в градусах (для точного расчета площади)
        :param pzz_config: словарь с параметрами ПЗЗ
        :param restrictions_geom: геометрия ограничений в метрах
        """
        self.parcel_geom = parcel_geom_meters
        self.parcel_geom_wgs84 = parcel_geom_wgs84
        self.pzz = pzz_config
        self.restrictions = restrictions_geom
        self.buildable_geom = None
        self.buildable_geom_wgs84 = None
        self.tep = {}
        self.financials = {}
        
        # Точный геодезический расчет площади участка
        self.real_area = calculate_geodesic_area(parcel_geom_wgs84)

    def calculate_buildable_area(self):
        """Вычисление строительного пятна с учетом отступов и ЗОУИТ"""
        # 1. Отступ от границ (в метрах)
        min_offset = self.pzz.get("min_offset_from_border", 0)
        buildable = self.parcel_geom.buffer(-min_offset)
        
        # 2. Вычитание ЗОУИТ (если есть)
        if self.restrictions is not None and not self.restrictions.is_empty:
            buildable = buildable.difference(self.restrictions)
        
        self.buildable_geom = buildable
        
        # Конвертируем обратно в WGS84 для точного расчета площади
        if buildable and not buildable.is_empty:
            self.buildable_geom_wgs84 = meters_to_wgs84(buildable)
            self.buildable_real_area = calculate_geodesic_area(self.buildable_geom_wgs84)
        else:
            self.buildable_geom_wgs84 = None
            self.buildable_real_area = 0
            
        return buildable

    def calculate_tep(self):
        """Расчет технико-экономических показателей"""
        if self.buildable_geom is None:
            self.calculate_buildable_area()
        
        # Используем реальную (геодезическую) площадь
        s_uch = self.real_area
        s_buildable = self.buildable_real_area
        
        max_density = self.pzz.get("max_building_density", 1.0)
        max_floors = self.pzz.get("max_floors", 1)
        floor_height = self.pzz.get("floor_height", 3.2)
        living_ratio = self.pzz.get("living_area_ratio", 0.7)
        norm_housing = self.pzz.get("norm_housing_per_person", 28.0)
        
        # Ограничение по плотности ПЗЗ
        s_zas_max = s_uch * max_density
        s_zas = min(s_buildable, s_zas_max)
        
        s_total = s_zas * max_floors
        s_living = s_total * living_ratio
        s_commercial = s_total - s_living
        population = math.floor(s_living / norm_housing) if norm_housing > 0 else 0
        
        self.tep = {
            "s_uch": round(s_uch, 1),
            "s_uch_ha": round(s_uch / 10000, 2),
            "s_buildable": round(s_buildable, 1),
            "s_zas": round(s_zas, 1),
            "s_total": round(s_total, 1),
            "s_living": round(s_living, 1),
            "s_commercial": round(s_commercial, 1),
            "floors": max_floors,
            "building_height_m": round(max_floors * floor_height, 1),
            "population": population,
            "schools": math.ceil((population / 1000) * 120),
            "kindergartens": math.ceil((population / 1000) * 60),
            "parking": math.ceil((s_total / 100) * 1.2),
            "green_space": math.ceil(population * 6)  # 6 м² на человека по нормативам
        }
        return self.tep

    def calculate_financials(self):
        """Расчет финансовых показателей"""
        if not self.tep:
            self.calculate_tep()
        
        cost_per_sqm = self.pzz.get("construction_cost_per_sqm", 80000)
        sale_price_per_sqm = self.pzz.get("sale_price_per_sqm", 200000)
        commercial_price_ratio = self.pzz.get("commercial_price_ratio", 0.8)
        land_cost = self.pzz.get("land_cost", 50000000)
        
        s_living = self.tep["s_living"]
        s_commercial = self.tep["s_commercial"]
        
        # Выручка
        revenue_living = s_living * sale_price_per_sqm
        revenue_commercial = s_commercial * sale_price_per_sqm * commercial_price_ratio
        total_revenue = revenue_living + revenue_commercial
        
        # Затраты
        construction_cost = self.tep["s_total"] * cost_per_sqm
        infra_cost = (self.tep["schools"] * 1500000 + 
                      self.tep["kindergartens"] * 1200000 + 
                      self.tep["parking"] * 800000)  # Примерная стоимость инфраструктуры
        total_cost = construction_cost + land_cost + infra_cost
        
        # Прибыль
        gross_profit = total_revenue - total_cost
        roi = (gross_profit / total_cost * 100) if total_cost > 0 else 0
        
        self.financials = {
            "revenue_living": round(revenue_living, 0),
            "revenue_commercial": round(revenue_commercial, 0),
            "total_revenue": round(total_revenue, 0),
            "construction_cost": round(construction_cost, 0),
            "infra_cost": round(infra_cost, 0),
            "land_cost": round(land_cost, 0),
            "total_cost": round(total_cost, 0),
            "gross_profit": round(gross_profit, 0),
            "roi_percent": round(roi, 1),
            "profit_per_sqm": round(gross_profit / self.tep["s_total"], 0) if self.tep["s_total"] > 0 else 0
        }
        return self.financials

# ============================================================================
# STREAMLIT ИНТЕРФЕЙС
# ============================================================================

st.set_page_config(page_title="Градостроительный Потенциал PRO", layout="wide")
st.title("🏙️ Анализатор градостроительного потенциала PRO")
st.markdown("**Полный комплексный анализ:** Точный расчет ТЭП + Финансы + 3D + Инсоляция + ЗОУИТ")

# ============================================================================
# ЗАГРУЗКА ДАННЫХ
# ============================================================================

st.header("📂 Загрузка территории")

data_source = st.radio(
    "Выберите источник данных:",
    ["Тестовый участок (пример)", "Загрузить свой файл"],
    horizontal=True
)

parcel_geom_meters = None
parcel_geom_wgs84 = None
restrictions_geom_meters = None

if data_source == "Загрузить свой файл":
    st.info("💡 Поддерживаемый формат: **GeoJSON** (.geojson, .json) в системе координат WGS84 (EPSG:4326)")
    
    # Основной участок
    uploaded_file = st.file_uploader(
        "1️⃣ Загрузите GeoJSON файл с границами участка",
        type=['geojson', 'json'],
        key="main_parcel"
    )
    
    # Ограничения (ЗОУИТ)
    uploaded_restrictions = st.file_uploader(
        "2️⃣ Загрузите GeoJSON с ограничениями (ЗОУИТ, красные линии) - *опционально*",
        type=['geojson', 'json'],
        key="restrictions"
    )
    
    if uploaded_file is not None:
        try:
            geojson_data = json.loads(uploaded_file.getvalue().decode("utf-8"))
            
            if geojson_data['type'] == 'FeatureCollection':
                geom_dict = geojson_data['features'][0]['geometry']
            elif geojson_data['type'] == 'Feature':
                geom_dict = geojson_data['geometry']
            else:
                geom_dict = geojson_data
            
            parcel_geom_wgs84 = shape(geom_dict)
            parcel_geom_meters = wgs84_to_meters(parcel_geom_wgs84)
            
            # Точный геодезический расчет
            real_area = calculate_geodesic_area(parcel_geom_wgs84)
            st.success(f"✅ Участок загружен! **Реальная площадь: {real_area:,.0f} м² ({real_area/10000:.2f} га)**")
            
            # Загрузка ограничений
            if uploaded_restrictions is not None:
                try:
                    restrictions_data = json.loads(uploaded_restrictions.getvalue().decode("utf-8"))
                    
                    if restrictions_data['type'] == 'FeatureCollection':
                        geoms = [shape(f['geometry']) for f in restrictions_data['features']]
                        restrictions_wgs84 = unary_union(geoms)
                    elif restrictions_data['type'] == 'Feature':
                        restrictions_wgs84 = shape(restrictions_data['geometry'])
                    else:
                        restrictions_wgs84 = shape(restrictions_data)
                    
                    restrictions_geom_meters = wgs84_to_meters(restrictions_wgs84)
                    restrictions_area = calculate_geodesic_area(restrictions_wgs84)
                    st.info(f"🚫 Загружены ограничения: **{restrictions_area:,.0f} м²** ({restrictions_area/10000:.2f} га)")
                    
                except Exception as e:
                    st.warning(f"⚠️ Не удалось загрузить ограничения: {str(e)}")
            
        except Exception as e:
            st.error(f"❌ Ошибка при чтении файла: {str(e)}")
            st.info("Убедитесь, что файл в формате GeoJSON и содержит валидную геометрию.")

else:
    st.info("Используется демонстрационный участок в центре Москвы")
    coords_wgs84 = [
        (37.61500, 55.75200),
        (37.61750, 55.75200),
        (37.61750, 55.75350),
        (37.61500, 55.75350)
    ]
    
    parcel_geom_wgs84 = Polygon(coords_wgs84)
    parcel_geom_meters = wgs84_to_meters(parcel_geom_wgs84)

# ============================================================================
# ПАРАМЕТРЫ ПЗЗ И ФИНАНСОВ
# ============================================================================

if parcel_geom_meters is not None:
    st.sidebar.header("⚙️ Градостроительные параметры")
    offset = st.sidebar.slider("Мин. отступ от границ (м)", 0, 30, 5, help="Отступ от красных линий")
    density = st.sidebar.slider("Макс. плотность застройки", 0.1, 1.0, 0.4, 0.05, help="Коэффициент застройки участка")
    floors = st.sidebar.slider("Предельная этажность", 1, 50, 9)
    floor_height = st.sidebar.slider("Высота этажа (м)", 2.8, 4.5, 3.2, 0.1)
    living_ratio = st.sidebar.slider("Доля жилой площади", 0.1, 1.0, 0.75, 0.05)
    norm_housing = st.sidebar.slider("Норма жилья на чел. (кв.м)", 15, 50, 28)
    
    st.sidebar.header("💰 Финансовые параметры")
    cost_per_sqm = st.sidebar.slider("Себестоимость (₽/м²)", 50000, 200000, 90000, 5000)
    sale_price = st.sidebar.slider("Цена продажи жилья (₽/м²)", 100000, 700000, 250000, 10000)
    commercial_ratio = st.sidebar.slider("Коэфф. цены коммерции", 0.5, 1.5, 0.85, 0.05)
    land_cost = st.sidebar.slider("Стоимость земли (млн ₽)", 0, 500, 50, 5)

    pzz_config = {
        "min_offset_from_border": offset,
        "max_building_density": density,
        "max_floors": floors,
        "floor_height": floor_height,
        "living_area_ratio": living_ratio,
        "norm_housing_per_person": norm_housing,
        "construction_cost_per_sqm": cost_per_sqm,
        "sale_price_per_sqm": sale_price,
        "commercial_price_ratio": commercial_ratio,
        "land_cost": land_cost * 1000000
    }

    # Запуск анализатора
    analyzer = UrbanPotentialAnalyzer(parcel_geom_meters, parcel_geom_wgs84, pzz_config, restrictions_geom_meters)
    tep = analyzer.calculate_tep()
    financials = analyzer.calculate_financials()
    buildable_geom_meters = analyzer.buildable_geom
    buildable_geom_wgs84 = analyzer.buildable_geom_wgs84

    # ========================================================================
    # ОТОБРАЖЕНИЕ ТЭП
    # ========================================================================
    
    st.header("📊 Технико-экономические показатели")
    
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Площадь участка", f"{tep['s_uch']:,.0f} м²", f"{tep['s_uch_ha']} га")
    col2.metric("Пятно застройки", f"{tep['s_buildable']:,.0f} м²")
    col3.metric("Общая площадь (GBA)", f"{tep['s_total']:,.0f} м²")
    col4.metric("Этажность", f"{tep['floors']} эт", f"{tep['building_height_m']} м")

    st.subheader("🏗️ Структура площадей")
    area_cols = st.columns(3)
    area_cols[0].info(f"🏠 **Жилая:** {tep['s_living']:,.0f} м² ({tep['s_living']/tep['s_total']*100:.1f}%)")
    area_cols[1].info(f"🏢 **Коммерция:** {tep['s_commercial']:,.0f} м² ({tep['s_commercial']/tep['s_total']*100:.1f}%)")
    area_cols[2].info(f"🌳 **Озеленение:** {tep['green_space']:,.0f} м²")

    st.subheader("👥 Социальная инфраструктура (потребность)")
    infra_cols = st.columns(4)
    infra_cols[0].info(f"👪 **Население:** {tep['population']:,} чел")
    infra_cols[1].info(f"🏫 **Школы:** {tep['schools']} мест")
    infra_cols[2].info(f"🧸 **Дет. сады:** {tep['kindergartens']} мест")
    infra_cols[3].info(f"🚗 **Парковка:** {tep['parking']} м/м")

    # ========================================================================
    # ФИНАНСОВЫЕ ПОКАЗАТЕЛИ
    # ========================================================================
    
    st.header("💰 Финансовая модель")
    
    fin_cols = st.columns(4)
    fin_cols[0].metric("Выручка (GDV)", f"{financials['total_revenue']/1000000:,.1f} млн ₽")
    fin_cols[1].metric("Затраты", f"{financials['total_cost']/1000000:,.1f} млн ₽")
    
    profit_color = "normal" if financials['gross_profit'] >= 0 else "inverse"
    fin_cols[2].metric(
        "Валовая прибыль", 
        f"{financials['gross_profit']/1000000:,.1f} млн ₽", 
        delta_color=profit_color
    )
    fin_cols[3].metric(
        "Рентабельность (ROI)", 
        f"{financials['roi_percent']}%", 
        delta_color=profit_color
    )

    with st.expander("📈 Детализация финансового расчета"):
        st.write(f"**Выручка от жилья:** {financials['revenue_living']/1000000:,.1f} млн ₽")
        st.write(f"**Выручка от коммерции:** {financials['revenue_commercial']/1000000:,.1f} млн ₽")
        st.write("---")
        st.write(f"**Затраты на строительство:** {financials['construction_cost']/1000000:,.1f} млн ₽")
        st.write(f"**Затраты на инфраструктуру:** {financials['infra_cost']/1000000:,.1f} млн ₽")
        st.write(f"**Стоимость земли:** {financials['land_cost']/1000000:,.1f} млн ₽")
        st.write("---")
        st.write(f"**💎 Прибыль с 1 м²:** {financials['profit_per_sqm']:,.0f} ₽")

    # ========================================================================
    # АНАЛИЗ ИНСОЛЯЦИИ
    # ========================================================================
    
    st.header("☀️ Анализ инсоляции")
    building_height = tep['building_height_m']
    
    # Определяем широту из геометрии участка
    centroid_wgs84 = parcel_geom_wgs84.centroid
    latitude = centroid_wgs84.y
    
    shadow_length = calculate_shadow_length(building_height, latitude)
    
    st.info(f"🏢 **Высота здания:** {building_height:.1f} м | **Широта:** {latitude:.2f}° | **Длина тени (зимн. солнцестояние):** {shadow_length:.1f} м")
    
    if shadow_length > 50:
        st.warning(f"⚠️ При высоте {building_height:.0f}м тень достигает **{shadow_length:.0f}м**. Рекомендуется провести детальную инсоляционную экспертизу!")
    
    if building_height > 75:
        st.error(f"🚨 Здание выше 75м требует обязательной разработки СТУ и специальных противопожарных решений")

    # ========================================================================
    # КАРТА
    # ========================================================================
    
    st.header("🗺️ Карта территории и строительного пятна")
    
    center_lat = centroid_wgs84.y
    center_lon = centroid_wgs84.x
    
    m = folium.Map(location=[center_lat, center_lon], zoom_start=16, tiles="OpenStreetMap")

    # GeoJSON для отображения
    parcel_geojson = {"type": "Feature", "properties": {"name": "Участок", "area_m2": tep['s_uch']}, "geometry": mapping(parcel_geom_wgs84)}

    # Исходный участок (Красный контур)
    folium.GeoJson(
        parcel_geojson,
        name="Границы участка",
        style_function=lambda x: {"fillColor": "gray", "fillOpacity": 0.1, "color": "red", "weight": 3},
        tooltip=folium.GeoJsonTooltip(fields=["name", "area_m2"], aliases=["Объект:", "Площадь:"])
    ).add_to(m)

    # Пятно застройки (Синий полигон)
    if buildable_geom_wgs84 is not None and not buildable_geom_wgs84.is_empty:
        buildable_geojson = {"type": "Feature", "properties": {"name": "Пятно застройки", "area_m2": tep['s_buildable']}, "geometry": mapping(buildable_geom_wgs84)}
        folium.GeoJson(
            buildable_geojson,
            name="Пятно застройки",
            style_function=lambda x: {"fillColor": "blue", "fillOpacity": 0.4, "color": "blue", "weight": 2},
            tooltip=folium.GeoJsonTooltip(fields=["name", "area_m2"], aliases=["Объект:", "Площадь:"])
        ).add_to(m)

    # Зона тени
    if shadow_length > 0 and buildable_geom_meters is not None:
        try:
            shadow_zone_meters = buildable_geom_meters.buffer(shadow_length)
            shadow_zone_wgs84 = meters_to_wgs84(shadow_zone_meters)
            shadow_geojson = {"type": "Feature", "properties": {"name": f"Зона тени ({shadow_length:.0f}м)"}, "geometry": mapping(shadow_zone_wgs84)}
            
            folium.GeoJson(
                shadow_geojson,
                name=f"Зона тени ({shadow_length:.0f}м)",
                style_function=lambda x: {"fillColor": "orange", "fillOpacity": 0.15, "color": "orange", "weight": 1, "dashArray": "5, 5"}
            ).add_to(m)
        except Exception as e:
            pass

    # Ограничения (если есть)
    if restrictions_geom_meters is not None:
        try:
            restrictions_wgs84 = meters_to_wgs84(restrictions_geom_meters)
            restrictions_geojson = {"type": "Feature", "properties": {"name": "Ограничения (ЗОУИТ)"}, "geometry": mapping(restrictions_wgs84)}
            folium.GeoJson(
                restrictions_geojson,
                name="Ограничения (ЗОУИТ)",
                style_function=lambda x: {"fillColor": "red", "fillOpacity": 0.3, "color": "darkred", "weight": 2, "dashArray": "3, 3"}
            ).add_to(m)
        except Exception as e:
            pass

    folium.LayerControl().add_to(m)
    st_folium(m, width=1200, height=600)

    # ========================================================================
    # ЭКСПОРТ ДАННЫХ
    # ========================================================================
    
    st.header("📥 Экспорт результатов")
    
    export_cols = st.columns(4)
    
    # Экспорт полного отчета (ТЭП + Финансы)
    with export_cols[0]:
        full_report = {
            "metadata": {
                "generated": datetime.now().isoformat(),
                "latitude": latitude,
                "longitude": center_lon
            },
            "tep": tep,
            "financials": financials,
            "pzz_parameters": pzz_config
        }
        st.download_button(
            label="📊 Полный отчет (JSON)",
            data=io.BytesIO(json.dumps(full_report, ensure_ascii=False, indent=2).encode()),
            file_name="urban_analysis_report.json",
            mime="application/json"
        )
    
    # Экспорт пятна застройки
    with export_cols[1]:
        if buildable_geom_wgs84 is not None:
            buildable_export = {
                "type": "FeatureCollection",
                "features": [{
                    "type": "Feature",
                    "properties": {
                        "name": "Пятно застройки",
                        "area_m2": tep['s_buildable'],
                        "area_ha": tep['s_buildable'] / 10000
                    },
                    "geometry": mapping(buildable_geom_wgs84)
                }]
            }
            st.download_button(
                label="🗺️ Пятно застройки (GeoJSON)",
                data=io.BytesIO(json.dumps(buildable_export, ensure_ascii=False, indent=2).encode()),
                file_name="buildable_area.geojson",
                mime="application/json"
            )
    
    # Экспорт 3D модели
    with export_cols[2]:
        obj_content = create_obj_file(buildable_geom_meters, building_height)
        if obj_content:
            st.download_button(
                label="🏢 3D модель (OBJ)",
                data=io.BytesIO(obj_content.encode()),
                file_name="building_3d.obj",
                mime="text/plain"
            )
        else:
            st.warning("3D недоступна")
    
    # Экспорт ТЭП в CSV
    with export_cols[3]:
        import csv
        csv_buffer = io.StringIO()
        writer = csv.writer(csv_buffer)
        writer.writerow(["Показатель", "Значение", "Ед.изм."])
        writer.writerow(["Площадь участка", tep['s_uch'], "м²"])
        writer.writerow(["Площадь участка", tep['s_uch_ha'], "га"])
        writer.writerow(["Пятно застройки", tep['s_buildable'], "м²"])
        writer.writerow(["Общая площадь", tep['s_total'], "м²"])
        writer.writerow(["Жилая площадь", tep['s_living'], "м²"])
        writer.writerow(["Коммерческая площадь", tep['s_commercial'], "м²"])
        writer.writerow(["Этажность", tep['floors'], "эт"])
        writer.writerow(["Высота здания", tep['building_height_m'], "м"])
        writer.writerow(["Население", tep['population'], "чел"])
        writer.writerow(["Школы", tep['schools'], "мест"])
        writer.writerow(["Детские сады", tep['kindergartens'], "мест"])
        writer.writerow(["Парковка", tep['parking'], "м/м"])
        writer.writerow(["Выручка", financials['total_revenue'], "₽"])
        writer.writerow(["Затраты", financials['total_cost'], "₽"])
        writer.writerow(["Прибыль", financials['gross_profit'], "₽"])
        writer.writerow(["ROI", financials['roi_percent'], "%"])
        
        st.download_button(
            label="📄 ТЭП в Excel (CSV)",
            data=io.BytesIO(csv_buffer.getvalue().encode('utf-8-sig')),
            file_name="tep_report.csv",
            mime="text/csv"
        )

    st.success("✅ Полный анализ завершен! Все данные готовы к экспорту.")

else:
    st.warning("⚠️ Загрузите файл с границами участка или выберите тестовые данные для начала анализа.")

st.markdown("---")
st.caption("🛠️ Urban Potential Analyzer PRO | Точный геодезический расчет на эллипсоиде WGS84")
